sudo: false
language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.6

otp_release:
  - 20.0

os:
  - linux

dist: trusty

addons:
  apt:
    packages:
    - libssh2-1-dev
    - cmake

env: PATH=$HOME/.cargo/bin:$PATH

cache:
  directories:
    - _build
    - deps

before_install:
  - kerl list installations
  - kerl list releases
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=1.19.0 -y
  - rustc --version
  - rustup --version
  - cargo --version
  - "./scripts/travisbuild.sh"
script:
  - mix test
  - mix dialyzer --halt-exit-status
