sudo: false
language: elixir
elixir:
  - 1.6.6

otp_release:
  - 20.0

os:
  - linux

addons:
  apt:
    packages:
    - libssh2-1-dev
    - cmake

env: PATH=$HOME/.cargo/bin:$PATH

cache:
  directories:
    - _build
    - deps

before_install:
  - kerl list installations
  - kerl list releases
  - cargo --version
  - "./scripts/travisbuild.sh"
script:
  - mix test
  - mix dialyzer --halt-exit-status
