sudo: false

language: rust

rust:
  - stable


cache: ~/libgit2

os:
  - linux

dist: trusty

addons:
  apt:
    packages:
    - libssh2-1-dev
    - cmake

env:
  - ELIXIR=1.3.4-1 LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
  - ELIXIR=1.4.5-1 LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib
  - ELIXIR=1.5.1-1 LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib


before_install:
  - "./scripts/travisbuild.sh"
  - wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends erlang elixir=$ELIXIR
  - mix local.hex --force
  - erl -version
  - elixir --version
  - mix --version
