sudo: false
language: elixir
elixir:
  - 1.3.0
  - 1.4.5

os:
  - linux

dist: trusty

addons:
  apt:
    packages:
    - libssh2-1-dev
    - cmake

git:
  submodules: false

before_install:
  - git submodule update --init
  - cd test/libgit2
  - cmake --build . --target install
