[package]
name = "gixir"
version = "0.1.0"
authors = []

[lib]
name = "gixir"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.17.1"
rustler_codegen = "0.17.1"
lazy_static = "1.0"
git2 = "0.7.2"
